### ISSUE TITLE
Display onion address to remotely access the dashboard

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#108]
Display onion address to remotely access the dashboard on the settings page, as well as after the onboarding is complete.

**Comment by nolim1t** [comment]
have you tested the dashboard performance in TOR?

**Comment by mayankchhabra** [comment]
Yeah, works well for me. 

Here's testnet dashboard: http://hvxuqp34limjqucjso3brkqi7kjzqpwhr3c4vsqjvbqb3lv6psv42rqd.onion

You should try it out too!

**Comment by mayankchhabra** [comment]
Could it be a JS issue?

**Comment by nolim1t** [comment]
possibly
