### ISSUE TITLE
Latest Blocks section is not refreshed to display actual synchronized blocks

### ISSUE THREAD

**Issue by Prabhudevaraju** [getumbrel/umbrel-dashboard#124]
![image](https://user-images.githubusercontent.com/7458733/86796091-cf185480-c0a0-11ea-9b83-6754d0d69fe1.png)
Latest Blocks section is not refreshed to display actual synchronized blocks.

**Comment by Prabhudevaraju** [comment]
Using Firefox 78.0.1

**Comment by mayankchhabra** [comment]
Thanks for reporting, will look into this.

**Comment by mayankchhabra** [comment]
Ok, it looks like this was due to faulty block fetching logic in dashboard <= v0.2.1. Tried on the latest code and I can't replicate the behavior, so the next release of the dashboard should fix this for you :)
