### ISSUE TITLE
Notify user about neutrino mode

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#129]
Add a notice somewhere on the lightning page that makes it clear that `lnd` is using `neutrino` until `bitcoind` sync is complete, and will automatically switch to it.

**Comment by nolim1t** [comment]
This can be left out of public beta if we don't have time for this. The value of this to a user who doesn't know the difference between either is good enough to leave out. And once there is OTA updates it is fine to patch  it in.

**Comment by mayankchhabra** [comment]
Closed by #170
