### ISSUE TITLE
3 dot setting icons, low contrast

### ISSUE THREAD

**Issue by sahilc0** [getumbrel/umbrel-dashboard#132]
**Issue**
On the gray background, 3 dot menu may have low contrast - particularly on the gray background
![image](https://user-images.githubusercontent.com/8256062/87254470-d2f8fd80-c437-11ea-9084-be00506fde76.png)

**Potential Solution**
Use [Stark](https://www.getstark.co/) to find a color that is more accessible

**Comment by sahilc0** [comment]
Hey @mayankchhabra this is very low priority, just wanted to add it here. Also was trying to suggest a more specific solution, but wasn't able to find the hex you used for bg and the alpha used on the icon - I'm a dummy :P  
![image](https://user-images.githubusercontent.com/8256062/87254554-4d298200-c438-11ea-8c40-c907181bbe0f.png)

**Comment by mayankchhabra** [comment]
Good feedback, we should make them darker. The color of the meatballs is in `fill` CSS value in your screenshot :P
