### ISSUE TITLE
Fat cards on wide-screen displays

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#141]
Someone put this on [twitter](https://twitter.com/bavarianledger/status/1286299240541691904):

![image](https://user-images.githubusercontent.com/10330103/88299154-adb19c80-cd1f-11ea-801f-e78a3e3f6637.png)

Those fat cards are in dire need of some cardio...

**Comment by meeDamian** [comment]
Perhaps just scale content proportionally?

**Comment by mayankchhabra** [comment]
Ah yes, although scaling using `transform: scale(x, y)` is very tricky when you consider both the upper and lower bound of displays, typography, etc. So we can't always scale pixel-to-pixel, but it does work really well right now from low-width to medium-width, and then gets fat as you increase the width further. 

I was thinking of capping the inner width of the content (all the stuff on the right which is not in the navigation bar), and since we use [bootstrap](https://bootstrap-vue.org/) we can just use their `container` class which does exactly that.
