### ISSUE TITLE
Fiat display on mobile vs desktop

### ISSUE THREAD

**Issue by shawnyeager** [getumbrel/umbrel-dashboard#156]
Noticed this.

**Here's Mobile Safari:**

![E166F82A-B279-4CFB-9009-6952DAA13EEE_1_105_c](https://user-images.githubusercontent.com/980297/88962582-41c5bb80-d26c-11ea-83d7-cc61d62c43c2.jpeg)

**And here's Chrome on macOS:**

<img width="755" alt="Screen Shot 2020-07-30 at 1 54 21 PM" src="https://user-images.githubusercontent.com/980297/88962642-54d88b80-d26c-11ea-921d-121908c05160.png">

**Comment by nolim1t** [comment]
Also seems to be like this over TOR

**Comment by mayankchhabra** [comment]
Thanks for reporting this, Shawn. 

It's probably a CORS issue with the API we use for the price feed, it's just inconsistent.

**Comment by nolim1t** [comment]
I think not displaying anything is the best if the api fails

**Comment by shawnyeager** [comment]
FWIW, I'm now seeing fiat displayed on desktop. Thought it was a browser thing, but clearly not.

**Comment by mayankchhabra** [comment]
Fixed by https://github.com/getumbrel/umbrel/pull/265
