### ISSUE TITLE
Use mempool.space's hidden service explorer when accessing via Tor

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-dashboard#164]
Use 
http://explorerzydxu5ecjrkwceayqybizmpjjznk5izmitf2modhcusuqlid.onion/
instead of
https://blockstream.info/

```javascript
if (window.location.host.indexOf(".onion") !== -1) { console.log("onion link"); } else { console.log("Not onion link"); }
```

**Comment by mayankchhabra** [comment]
We switched to mempool.space (#260), but feel free to add support for mempool's hidden service url if you want to.
