### ISSUE TITLE
Display LND channel info on dashboard homepage

### ISSUE THREAD

**Issue by P-Verbrugge** [getumbrel/umbrel-dashboard#165]
Would it be possible to Just a thought: Would it be possible to display the number of channels on the homepage? 

Now you always have to go to the lightning page. The LND section could be smaller in my opinion and the free space could be used to display some channel info.

**Comment by mayankchhabra** [comment]
Sounds good, although we want to keep the homepage as clean as possible. I'm not sure if reducing the one-click to see the channel info will have any significant upside.
