### ISSUE TITLE
Wrap big balances

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#183]
<img width="639" alt="Screenshot 2020-08-20 at 17 03 06" src="https://user-images.githubusercontent.com/10330103/90757101-cdc28480-e2fa-11ea-9488-2eaa2b73c8d5.png">

h/t @lukechilds

**Comment by jgmontoya** [comment]
I wish I had this issue :joy:

**Comment by mayankchhabra** [comment]
well it's more of a feature than an issue since it discourages people to store large amounts of funds on their Umbrel haha
