### ISSUE TITLE
Discard old blocks cached in the browser memory for better performance

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#195]
Because it does this: https://github.com/getumbrel/umbrel-dashboard/issues/245

**Comment by EddWills95** [comment]
If I understand this right, I think this is related to: https://github.com/getumbrel/umbrel-dashboard/issues/245

How many blocks should we keep in the browser? I guess we only need 6 in the browser at any one time for the animation to work?

**Comment by mayankchhabra** [comment]
@EddWills95 yes, it's probably what is causing #245. 

You're right, 6 blocks is all we need for the animation to work.

**Comment by EddWills95** [comment]
Had a crack: https://github.com/getumbrel/umbrel-dashboard/pull/253
