### ISSUE TITLE
[Bug] Stuck at Loading screen

### ISSUE THREAD

**Issue by sahilc0** [getumbrel/umbrel-dashboard#197]
Raspi 3. 

After turning on raspi with umbrel flashed on SD card, I am getting stuck on this screen:
![image](https://user-images.githubusercontent.com/8256062/91776917-5961ce00-eba3-11ea-81a4-43339f7e03eb.png)

Any idea why? Is there a log file I can share that might help?

**Comment by sahilc0** [comment]
Update - i did
`docker-compose logs -f bitcoin`

and I see this:
![image](https://user-images.githubusercontent.com/8256062/91778269-ca56b500-eba6-11ea-8828-0f0999629f6d.png)


Does this just mean it's still syncing the chain?

**Comment by nolim1t** [comment]
Raspberry PI3?

Give it some time. Around block 300k processing gets heavy

**Comment by mayankchhabra** [comment]
That sucks man. It does look like it's syncing the chain, but the dashboard should nonetheless be accessible. Curious what version of Umbrel OS are you on? Because it looks like it's not one of the latest versions (we added status text to the loading progress bar) and there was a recent performance improvement we made for Pi 3 so not sure if you're able to leverage it.

**Comment by sahilc0** [comment]
@nolim1t true! I just remember seeing the dashboard earlier, now it's just this loading screen.

@mayankchhabra Honestly not sure - it was from a while ago! But I do remember getting into the dashboard to see it syncing and I could play around with it. Now it's getting stuck here. 

Also - woke up this morning and tried to get the logs, but wasn't able to ssh:
![image](https://user-images.githubusercontent.com/8256062/91873030-6cb97b80-ec2d-11ea-9be9-037ef3d3e82e.png)
Might be useful to know @mayankchhabra - this was happening a lot before, and the "solution" was always to unplug and plug back in. It would sync blocks again, and then get stuck like it is now.

Do you think it's worth re-flashing the most updated software?

**Comment by nolim1t** [comment]
There are performance issues with raspberry pi 3 around the 300k mark when doing IBD

**Comment by mayankchhabra** [comment]
@sahilc0 So it looks like it's running out of RAM again. Totally recommend trying out the [latest image](https://github.com/getumbrel/umbrel-os/releases/latest). The recent performance improvement (https://github.com/getumbrel/umbrel/pull/180) we made was specifically targeted towards Raspberry Pi 3 so there's a good chance it'd work without a problem this time around (I hope).

**Comment by sahilc0** [comment]
@mayankchhabra So far this worked - will report back and close if it syncs up fine!

**Comment by sahilc0** [comment]
OK I think this did the trick. Will reopen if still an issue. Thanks Mayank
