### ISSUE TITLE
[FEATURE REQUEST] Translations

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel-dashboard#212]
Translations would help make Umbrel more accessible. I could provide a German translation, but I can't implement a translation feature because I don't know Vue, and I'm currently working on other projects and wouldn't have time to implement it if I knew Vue.

**Comment by jgmontoya** [comment]
I can help with spanish translations for when the time comes!

**Comment by nolim1t** [comment]
I suggest using transifex for crowdsourced localizations.

**Comment by System-Glitch** [comment]
I would gladly contribute and work on the french translations.

**Comment by louneskmt** [comment]
See this (for now): https://github.com/getumbrel/umbrel-dashboard/issues/264#issuecomment-739814596
