### ISSUE TITLE
Mining Fee sats don't change with slider

### ISSUE THREAD

**Issue by shaggy35** [getumbrel/umbrel-dashboard#223]
When withdrawing from main wallet or when setting confirmation fee on opening LN channel  the sat value doesn't change with slider 

<img width="437" alt="Screenshot 2020-09-27 at 14 56 53" src="https://user-images.githubusercontent.com/70859242/94366676-b03ec280-00d1-11eb-92f0-235b1fe95999.png">

<img width="455" alt="Screenshot 2020-09-27 at 14 57 14" src="https://user-images.githubusercontent.com/70859242/94366682-bcc31b00-00d1-11eb-80a3-117475e80cc5.png">

**Comment by mayankchhabra** [comment]
This is a known issue with the way LND calculates fee for target block confirmations, so there's not much we can do here (other than removing our dependency from LND's in-built fee calculation and doing our own, which isn't worth the effort for now). Although at times when the mempool is empty, all the estimates are naturally the same.
