### ISSUE TITLE
Improve Slider Fee Display

### ISSUE THREAD

**Issue by shaggy35** [getumbrel/umbrel-dashboard#224]
I quite like the info Wasabi gives on mining fees. Not only granularity of the slider but also the 'value'. By clicking on the value the display can be changed from btc, sats and usd

<img width="751" alt="Screenshot 2020-09-27 at 15 03 50" src="https://user-images.githubusercontent.com/70859242/94366852-ab2e4300-00d2-11eb-986e-d5a6ff90b063.png">

<img width="384" alt="Screenshot 2020-09-27 at 15 01 26" src="https://user-images.githubusercontent.com/70859242/94366767-52f74100-00d2-11eb-8b40-4a56a4faeee4.png">

<img width="420" alt="Screenshot 2020-09-27 at 15 02 58" src="https://user-images.githubusercontent.com/70859242/94366829-8a65ed80-00d2-11eb-8c01-47aafd3f7677.png">

slider granularity is 

20 mins
30 mins
40 mins
50 mins
60 mins
1 hour - 24 hours
1-2 days

**Comment by mayankchhabra** [comment]
Thanks, @shaggy35. We added support for custom fee for more fine grained control (https://github.com/getumbrel/umbrel-dashboard/pull/236) along with Sats and USD estimates so we can keep the default slider as simple as possible.
