### ISSUE TITLE
Calculate percentage of downloaded blockchain by size and not by number of blocks

### ISSUE THREAD

**Issue by petrhejna** [getumbrel/umbrel-dashboard#242]
The 50% of all blocks is only 31GB (~10%) of the size. And when user is downloading blockchain the relevant number is the percentage of gigs.

![image](https://user-images.githubusercontent.com/383295/96047779-e9b75200-0e75-11eb-8fcf-21f9de860ed0.png)

Alternatively both numbers can be shown, but I suggest to make the gigs% the main (bigger) one.

Related to #225

**Comment by mayankchhabra** [comment]
Thank you, @petrhejna. Closing this as we're tracking a duplicate issue (https://github.com/getumbrel/umbrel/issues/243)
