### ISSUE TITLE
Block alidation animation spins CPU like crazy

### ISSUE THREAD

**Issue by petrhejna** [getumbrel/umbrel-dashboard#245]
It appears that during blockchain sync the dashboard animation (blocks poping up) consumes a lot of CPU.

![image](https://user-images.githubusercontent.com/383295/96112942-b0b5c680-0ee3-11eb-8efa-0522dc61378d.png)

**Comment by mayankchhabra** [comment]
Thanks, @petrhejna! There's an open issue (#195) for this and hopefully will be fixed soon (#253).
