### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by System-Glitch** [getumbrel/umbrel-dashboard#264]
Umbrel is great and simple but is, as far as I know, only available in english. Are there any plans for localisation? Supporting multiple languages would make it even more accessible to everyone.

I would gladly contribute and work on the french translations.

**Comment by System-Glitch** [comment]
Sorry for the duplicate #212

**Comment by louneskmt** [comment]
Hey! I've started working on localisations in Umbrel, but this has been delayed as it adds complexity to the code (e.g. you need to handle each text as a variable) which will slow down the development of major features. 

Umbrel is still in beta version, so translations are not the priority right now and will not be implemented until it gets out of beta (but the code is ready 😁).
