### ISSUE TITLE
Balance USD amount sometimes display ~ $NaN

### ISSUE THREAD

**Issue by rubenhbaca** [getumbrel/umbrel-dashboard#268]
![image](https://user-images.githubusercontent.com/19667830/102683503-e5b5f200-418e-11eb-89b2-2ae6606985f7.png)

**Comment by rubenhbaca** [comment]
I will fix this later, I am just documenting my finding here for later reference.

**Comment by louneskmt** [comment]
That is a known issue : the price is fetched via Tor. We talked about this in the Keybase dev chat with @lukechilds. Sometimes the request is refused by the API. A workaround could be to save the last fetched price and return it in case of a request error.

**Comment by rubenhbaca** [comment]
Yes, that would be a great workaround. Where do you suggest this hardening code should be, dashboard (client-side) or where we make the call to the API (server-side)? It can easily be done on the client side. Just not sure on your guyses philosophy on server vs client-side code (but ill get there).

I can always not display the amount it if it's not a number as another workaround?

**Comment by louneskmt** [comment]
Here is the scheme to get the price:

Dashboard --API--> Manager --API via Tor--> Cryptocompare

I think the best way to do it could be to have the manager save the price when it is successfully retrieved. So when the request is unsuccessful (for example because of the tor current identity), the manager returns the saved price to the dashboard instead of nothing.

**Comment by rubenhbaca** [comment]
Yea that sounds great.

**Comment by louneskmt** [comment]
Here is the route: https://github.com/getumbrel/umbrel-manager/blob/master/routes/v1/external.js

**Comment by rubenhbaca** [comment]
Yes that exactly the place to put the fix. I'll make a PR later tonight.

**Comment by rubenhbaca** [comment]
@louneskmt I have created a PR as promised.
https://github.com/getumbrel/umbrel-manager/pull/62

**Comment by bezysoftware** [comment]
Any plans merging this?

**Comment by rubenhbaca** [comment]
I hope so. poke @mayankchhabra @louneskmt

**Comment by lukechilds** [comment]
Sorry for the delay, missed this, reviewed your PR @rubenhbaca!

**Comment by rubenhbaca** [comment]
@lukechilds thank you, I will review and make those changes tonight.

**Comment by TannerR1776** [comment]
@rubenhbaca Any plans to finish the PR for this bug? If not, I would be happy to work on this issue. Thanks!

**Comment by rubenhbaca** [comment]
@TannerR1776 i will review this PR tonight and see if there is any further changes and pump luke for a merge.
