### ISSUE TITLE
High CPU usage on dashboard/bitcoin during IBD

### ISSUE THREAD

**Issue by mutatrum** [getumbrel/umbrel-dashboard#277]
I notices high CPU usage on the bitcoin tab during IBD. The Chrome taskmanager shows continues 150% CPU usage, even though the recent blocks display is updated once a second. At points, the whole browser locks up until I close the umbrel tab, the machine becomes responsive almost immediately.

I tried debugging, and found back-to-back animation and compositor tasks. My suspicion is that it's either the spinning blue cube animation and/or coupled with a DOM that has a lot of invisible elements. At some point the IBD stalled due to dropped connections which resulted in the CPU load of the tab dropping to 40%.

As my machine was locking up, I couldn't make a screenshot, only a photo. This shows a DOM with around 30 elements of recent blocks, even though only 3 are shown.

Further observations are that the umbrel browser tab when showing the bitcoin status have a tendency to crash with an Error 9 from Chrome. This happened several times in a few hours.

![PXL_20210104_234440990 MP](https://user-images.githubusercontent.com/56344102/103591277-f8029080-4eef-11eb-85e0-2a6401738afd.jpg)

Chrome 87.0.4280.88 (64-bit) on Ubuntu 20.04.

**Comment by louneskmt** [comment]
Hey! 

A PR fixing this issue is already opened and will be included in a next version: https://github.com/getumbrel/umbrel-dashboard/pull/253

Sorry I totally forgot about it when we discussed about this on Telegram.

**Comment by mutatrum** [comment]
Ah thanks, I missed that one before opening this one. Closing this one.
