### ISSUE TITLE
Performance Fix: Remove old items in "Latest Blocks" 

### ISSUE THREAD

**Issue by hitchcott** [getumbrel/umbrel-dashboard#278]
I noticed that if I wait for a while, the dashboard becomes sluggish (the animation framerate drops and interaction is less responsive).

After peeking at the DOM it looks like this might be the issue:

![image](https://user-images.githubusercontent.com/1696942/103717315-bceb8480-4ff7-11eb-9d7d-0dabb81595a8.png)

Currently, the a new DOM element per block is created and is not removed even when navigating pages, so left for a long time (especially during sync), this adds up to thousands of elements which strains the browser.

To fix this, simply limit the number of items rendered here to 6 - it only ever needs to shows 3 + 3 animating at a time.

**Comment by louneskmt** [comment]
Hey! Thanks for reporting this. 

A PR fixing this issue is already opened and will likely be included in a next version: #253

**Comment by hitchcott** [comment]
Ah, sorry I missed this is a duplicate.
