### ISSUE TITLE
Add custom explorer link

### ISSUE THREAD

**Issue by jrosco** [getumbrel/umbrel-dashboard#290]
Would it be possible to add a custom link to use a different explorer from the dashboard? So when I click on a transaction it redirects to a custom explorer URL.

It currently redirects to mempool.space/tx/[tx_id].

As a user I may decide I want to use smartbit.com.au/tx/ or the locally installed explorer app.

What would be cool if it detected that the BTC RPC Explorer container is installed and used this instead of the default one.

**Comment by louneskmt** [comment]
It's planned to detect if a self hosted explorer is installed on Umbrel, and redirect to it if it's the case. 

Related: https://github.com/getumbrel/umbrel/issues/435
