### ISSUE TITLE
Option to set custom transaction fee disabled when withdrawing from Bitcoin wallet

### ISSUE THREAD

**Issue by johngribbin** [getumbrel/umbrel-dashboard#307]
<img width="474" alt="Screen Shot 2021-02-15 at 6 37 05 PM" src="https://user-images.githubusercontent.com/30157175/108011136-74e75680-6fd4-11eb-8100-aea39915c21d.png">

Note - I was sending to a multisig address. Could this have had any impact?

**Comment by lukechilds** [comment]
This looks like it could be a bug in the latest release, users are having issues opening channels too.

For now you can work around it by using the RTL or Thunderhub apps to make payments.

Looking into it!
