### ISSUE TITLE
Developers

### ISSUE THREAD

**Issue by mwager** [getumbrel/umbrel-dashboard#319]
Hey guys,

are you looking for devs? Plus: is it possible to get involved and earning money (or better bitcoin)?

I am a web developer with 12 years experience (esp. javascript) and just set up my umbrel. I love your work and I love vue.js ❤️

I could support (almost) full time.

Regards, 
Michael

**Comment by mayankchhabra** [comment]
Hi Michael, happy to hear that! Feel free to share links to whatever you consider some of your best work(s) so far.

If you can't make it public, you can send it to me at mayank@getumbrel.com.

**Comment by mwager** [comment]
I sent you an email, closing here :)
