### ISSUE TITLE
Unable to connect Ledger to node using RPC Auth in bitcoin config file

### ISSUE THREAD

**Issue by josephwar** [getumbrel/umbrel-dashboard#324]
While using instructions from ledger, it asks for rpcuser=<user> ; rpcpassword=<password> from the bitcoin config file. 
It shows no such thing. 
Unable to connect with RPCauth = <user>:<hash>$<hash>$

**Comment by louneskmt** [comment]
You can find connections details in Dashboard > Connect wallet > Bitcoin RPC

**Comment by josephwar** [comment]
Thank you.
