### ISSUE TITLE
Suggestion : Adding a DID 

### ISSUE THREAD

**Issue by Koploseus** [getumbrel/umbrel-dashboard#384]
Hello,

Would be amazing to add in getumbrel a DID (a real one like elastos ) fully decentralized, and use the lighting network wallet to access decentralized storage , decentralized twitter or else.

I'm talking about real decentralized stuff.

**Comment by jonsyu** [comment]
Closing since we've recorded this feature request, DIDs are a great idea and something we'd love to have at some point.
