### ISSUE TITLE
Add Alby wallet connection instructions

### ISSUE THREAD

**Issue by bumi** [getumbrel/umbrel-dashboard#389]
[Alby](https://github.com/getAlby/lightning-browser-extension) is a browser extension that makes it easy to use lightning from the browser.
Alby can connect to LND directly or to a LNDHub. 
We should offer Umbrel users instructions on how to connect Umbrel to the browser extension. 

As also discussed in: https://github.com/getumbrel/umbrel/issues/1021

**Comment by jonsyu** [comment]
Closing because we've recorded this request - thanks for the suggestion (trying to find a better place to store these type of documentation requests as well)
