### ISSUE TITLE
I can't see my address

### ISSUE THREAD

**Issue by maginkgo** [getumbrel/umbrel-dashboard#394]
Use these commands to switch to testnet:

It turns out that afterwards, everything seems to work fine except that it doesn't show me the bitcoin address.

```
sudo ./scripts/stop
sudo systemctl stop umbrel-startup

sudo rm ~/umbrel/.env
sudo rm ~/umbrel/statuses/configured

sudo NETWORK=testnet ./scripts/configure

sudo rm -r ~/umbrel/lnd/!(lnd.conf) 
sudo rm ~/umbrel/db/user.json
sudo rm -r ~/umbrel/db/umbrel-seed/seed

sudo systemctl start umbrel-startup
```
I went back to mainnet mode but the problem persists. 

[See image](https://imgur.com/XcNnkQ0)

What could I have broken and how could I fix it? Thanks

**Comment by jonsyu** [comment]
Are you having this issue still? I know it's been awhile - if so, please ask about it on our community forum (https://community.getumbrel.com), there's likely more people who might have tried this there already. Closing for now, thanks!
