### ISSUE TITLE
[Suggestion] Select password input field on login page load and wrong password input

### ISSUE THREAD

**Issue by stakingpoolspace** [getumbrel/umbrel-dashboard#429]
Hey everyone, I would like to propose a small quality of life improvement: automatically selecting the password input field whenever the login page loads and whenever you try to login with a wrong password.

I have a long password that I manually type out and sometimes introduce a typo to, I then either have to use my mouse or tab my way back to the password input field, ctrl + A to select the whole input field and then retype my password.

It would be so much easier to have Vue handle this automatically. I already have the code ready to add this, but I am opening an Issue for this as per the Contributing guidelines.

P.s. I know there's a merge request (#392) with the same kind of idea, but it's outdated

**Comment by mayankchhabra** [comment]
Sounds like a great idea! Thanks for the suggestion. Feel free to open a PR if you'd like to work on it.
