### ISSUE TITLE
Feedback:  Change username feature in settings

### ISSUE THREAD

**Issue by jimbrend** [getumbrel/umbrel-dashboard#445]
Had several contacts regarding an easier way to change your Umbrel dashboard's username. 

Currently, we have these steps but users seem to get lots of errors when attempting it manually with this command: 

`echo "$( jq '.name = "NEWNAME"' ~/umbrel/db/user.json )" > ~/umbrel/db/user.json`

Replace NEWNAME with the desired username (including the quotation marks surrounding username).

I've been more successful with users when we change it like this as well: 

`sudo nano umbrel/db/user.json`

Then after it takes them to their user.json file we edit the top line that looks like this:
"name": "YourUsername",

This seems like something easy we can implement, to add a feature to change it in settings?

**Comment by mayankchhabra** [comment]
Duplicate: https://github.com/getumbrel/private-umbrel/issues/126
